#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 30 18:05:34 2012

@author: chauvet

wx interface for granulometrie

version: 14.06.2013

** version log **

* 14.06.2013 *
- Add more information to export format
- correct scale bug in loading image

"""

import wx

from LibPyCalliper.MainWindows import ProjectManager

#Launch the wx application
app = wx.App()
a = ProjectManager(None)
app.MainLoop()

